const STORAGE={workouts:'workoutDefinitions',days:'workoutLogs',activities:'activityLogs',customExercises:'customExercises',customActivities:'customActivities'};
const catalog={
'Stretching':[
['Neck Stretch','Neck / upper traps',2,'20–30 sec',2.3,'Move gently; no bouncing.'],['Shoulder Stretch','Shoulders / chest',2,'20–30 sec',2.3,'Stay below pain.'],['Doorway Chest Stretch','Chest / shoulders',2,'20–30 sec',2.3,'Keep ribs down.'],['Triceps Stretch','Triceps / shoulders',2,'20–30 sec',2.3,'Do not force the elbow.'],['Forearm Stretch','Forearms / wrists',2,'20–30 sec',2.3,'Useful after gripping work.'],['Cat-Cow','Spine mobility',2,'8–12',2.5,'Move slowly through a comfortable range.'],['Child’s Pose','Back / hips',2,'20–45 sec',2.3,'Breathe into the back ribs.'],['Hip Flexor Stretch','Hip flexors',2,'20–30 sec/side',2.3,'Tuck pelvis gently.'],['Hamstring Stretch','Hamstrings',2,'20–30 sec/side',2.3,'Keep spine long.'],['Quadriceps Stretch','Quadriceps',2,'20–30 sec/side',2.3,'Keep knees near each other.'],['Figure-Four Stretch','Glutes / hips',2,'20–30 sec/side',2.3,'Stop if knee pain.'],['Calf Stretch','Calves',2,'20–30 sec/side',2.3,'Keep heel grounded.'],['Adductor Stretch','Inner thighs',2,'20–30 sec',2.3,'Shift gradually.'],['Thoracic Rotation','Upper back',2,'8–10/side',2.5,'Rotate from upper back.'] ],
'Gym Machines':[
['Leg Press','Quads / glutes',3,'8–12',5.0,'Control depth and avoid locking knees.'],['Hack Squat Machine','Quads / glutes',3,'8–12',5.5,'Keep back supported.'],['Leg Extension','Quads',3,'10–15',4.0,'Pause at the top.'],['Seated Leg Curl','Hamstrings',3,'10–15',4.0,'Control the return.'],['Lying Leg Curl','Hamstrings',3,'10–15',4.0,'Keep hips down.'],['Hip Abductor','Glutes / hips',3,'12–20',3.5,'Avoid bouncing.'],['Hip Adductor','Inner thighs',3,'12–20',3.5,'Use a controlled range.'],['Glute Drive Machine','Glutes',3,'8–15',4.5,'Squeeze at the top.'],['Standing Calf Raise Machine','Calves',3,'12–20',4.0,'Use full range.'],['Seated Calf Raise Machine','Calves',3,'12–20',3.8,'Pause at the top.'],['Chest Press Machine','Chest / triceps',3,'8–12',4.5,'Keep shoulders down.'],['Incline Chest Press Machine','Upper chest / triceps',3,'8–12',4.5,'Do not flare elbows excessively.'],['Pec Deck Fly','Chest',3,'10–15',4.0,'Stretch gently, then squeeze.'],['Rear Delt Fly Machine','Rear delts / upper back',3,'10–15',4.0,'Lead with elbows.'],['Shoulder Press Machine','Shoulders / triceps',3,'8–12',4.5,'Stop if shoulder pain.'],['Lateral Raise Machine','Side delts',3,'10–15',3.8,'Use light, strict reps.'],['Lat Pulldown','Lats / biceps',3,'8–12',4.5,'Pull elbows down.'],['Assisted Pull-Up','Lats / biceps',3,'6–12',5.0,'Use smooth reps.'],['Seated Row Machine','Mid back / biceps',3,'8–12',4.5,'Squeeze shoulder blades.'],['High Row Machine','Upper back / lats',3,'8–12',4.5,'Keep chest supported.'],['Low Row Machine','Mid back / lats',3,'8–12',4.5,'Pull toward lower ribs.'],['Biceps Curl Machine','Biceps',3,'10–15',3.5,'Keep upper arms fixed.'],['Triceps Extension Machine','Triceps',3,'10–15',3.5,'Avoid shoulder movement.'],['Triceps Dip Machine','Triceps / chest',3,'8–12',4.2,'Control the bottom.'],['Abdominal Crunch Machine','Abs',3,'10–20',3.5,'Curl ribs toward pelvis.'],['Back Extension Machine','Lower back / glutes',3,'10–15',3.5,'Avoid overextension.'],['Rotary Torso Machine','Obliques',3,'10–15/side',3.5,'Use a controlled range.'] ],
'Free Weights':[
['Goblet Squat','Quads / glutes',3,'8–15',5.5,'Hold weight close to chest.'],['Dumbbell Squat','Quads / glutes',3,'8–15',5.5,'Keep knees tracking toes.'],['Barbell Back Squat','Quads / glutes',3,'5–10',6.0,'Brace before each rep.'],['Romanian Deadlift','Hamstrings / glutes',3,'8–12',5.5,'Hinge at hips.'],['Conventional Deadlift','Posterior chain',3,'3–8',6.0,'Keep load close to body.'],['Dumbbell Lunge','Legs / glutes',3,'8–12/side',5.5,'Use a stable stride.'],['Bulgarian Split Squat','Quads / glutes',3,'8–12/side',6.0,'Keep front foot planted.'],['Dumbbell Step-Up','Legs / glutes',3,'8–12/side',5.5,'Drive through the working leg.'],['Dumbbell Bench Press','Chest / triceps',3,'8–12',5.0,'Keep shoulder blades set.'],['Incline Dumbbell Press','Upper chest / triceps',3,'8–12',5.0,'Control the descent.'],['Dumbbell Fly','Chest',3,'10–15',4.5,'Use a slight elbow bend.'],['Dumbbell Shoulder Press','Shoulders / triceps',3,'8–12',5.0,'Avoid arching the back.'],['Dumbbell Lateral Raise','Side delts',3,'10–20',4.0,'Raise with control.'],['Dumbbell Front Raise','Front delts',3,'10–15',4.0,'Do not swing.'],['Bent-Over Dumbbell Row','Back / biceps',3,'8–12',5.0,'Keep torso stable.'],['One-Arm Dumbbell Row','Lats / biceps',3,'8–12/side',5.0,'Pull toward hip.'],['Dumbbell Pullover','Lats / chest',3,'10–15',4.5,'Keep ribs controlled.'],['Dumbbell Biceps Curl','Biceps',3,'8–15',4.0,'No swinging.'],['Hammer Curl','Biceps / forearms',3,'8–15',4.0,'Use neutral grip.'],['Dumbbell Triceps Extension','Triceps',3,'8–15',4.0,'Keep elbows steady.'],['Dumbbell Skull Crusher','Triceps',3,'8–15',4.0,'Lower carefully.'],['Dumbbell Calf Raise','Calves',3,'12–25',4.0,'Pause at the top.'],['Farmer Carry','Grip / core / traps',3,'30–60 sec',6.0,'Walk tall.'],['Suitcase Carry','Core / grip',3,'30–60 sec/side',5.5,'Do not lean.'] ],
'Aerobics':[
['Treadmill Walk','Cardio',1,'minutes',3.5,'Choose a sustainable pace.'],['Treadmill Brisk Walk','Cardio',1,'minutes',4.8,'Use a natural stride.'],['Treadmill Incline Walk','Cardio / glutes',1,'minutes',6.0,'Avoid holding the rails.'],['Treadmill Jog','Cardio',1,'minutes',7.0,'Build gradually.'],['Treadmill Run','Cardio',1,'minutes',9.0,'Use appropriate footwear.'],['Elliptical','Cardio / full body',1,'minutes',5.0,'Keep motion smooth.'],['Stationary Bike','Cardio / legs',1,'minutes',5.5,'Adjust seat height.'],['Recumbent Bike','Cardio / legs',1,'minutes',4.5,'Keep cadence steady.'],['Stair Climber','Cardio / legs',1,'minutes',8.0,'Stand tall.'],['Rowing Machine','Cardio / full body',1,'minutes',7.0,'Drive with legs first.'],['Ski Erg','Cardio / upper body',1,'minutes',7.0,'Hinge rather than squat.'],['Step Aerobics','Cardio / legs',1,'minutes',7.0,'Use a safe step height.'],['Low-Impact Aerobics','Cardio',1,'minutes',4.5,'Keep one foot grounded.'],['High-Impact Aerobics','Cardio',1,'minutes',7.5,'Modify jumps as needed.'],['Jump Rope','Cardio',1,'minutes',10.0,'Use short intervals.'] ],
'Swimming':[
['Easy Lap Swimming','Full body / cardio',1,'minutes',5.8,'Use relaxed technique.'],['Moderate Lap Swimming','Full body / cardio',1,'minutes',7.0,'Maintain a steady pace.'],['Vigorous Lap Swimming','Full body / cardio',1,'minutes',9.8,'Use intervals if needed.'],['Freestyle','Full body / cardio',1,'minutes',8.3,'Keep breathing rhythmic.'],['Breaststroke','Full body / cardio',1,'minutes',10.3,'Use smooth timing.'],['Backstroke','Back / cardio',1,'minutes',7.0,'Keep hips high.'],['Butterfly','Full body / cardio',1,'minutes',13.8,'Best for trained swimmers.'],['Water Walking','Cardio / joints',1,'minutes',4.5,'Use chest-deep water.'],['Water Aerobics','Cardio / resistance',1,'minutes',5.5,'Move continuously.'],['Treading Water','Cardio / full body',1,'minutes',7.0,'Use efficient sculling.'] ],
'Isometrics':[
['Wall Sit','Quads / glutes',3,'20–60 sec',4.0,'Keep knees comfortable.'],['Plank','Core',3,'20–60 sec',3.8,'Brace abs and glutes.'],['Side Plank','Obliques / shoulders',3,'15–45 sec/side',3.8,'Keep body straight.'],['Glute Bridge Hold','Glutes / hamstrings',3,'20–60 sec',3.5,'Squeeze glutes.'],['Split Squat Hold','Legs / glutes',3,'15–45 sec/side',4.5,'Use support if needed.'],['Calf Raise Hold','Calves',3,'15–45 sec',3.5,'Hold near the top.'],['Push-Up Hold','Chest / triceps / core',3,'10–30 sec',4.0,'Choose a safe elbow angle.'],['Chest Press Isometric','Chest / arms',3,'10–30 sec',3.5,'Press palms or object firmly.'],['Biceps Curl Isometric','Biceps',3,'10–30 sec',3.5,'Hold near 90 degrees.'],['Triceps Extension Isometric','Triceps',3,'10–30 sec',3.5,'Keep shoulder still.'],['Towel Row Isometric','Back / biceps',3,'10–30 sec',3.8,'Pull evenly.'],['Shoulder External Rotation Hold','Rotator cuff',3,'10–30 sec',3.0,'Use gentle tension.'],['Dead Bug Hold','Core',3,'10–30 sec/side',3.5,'Keep lower back controlled.'],['Hollow Body Hold','Core',3,'10–30 sec',4.0,'Regress by bending knees.'],['Superman Hold','Back / glutes',3,'10–30 sec',3.5,'Lift only slightly.'] ],
'Resistance Bands':[
['Band Squat','Quads / glutes',3,'10–20',4.5,'Stand securely on band.'],['Band Romanian Deadlift','Hamstrings / glutes',3,'10–20',4.5,'Hinge at hips.'],['Band Glute Bridge','Glutes',3,'12–20',4.0,'Keep knees pressing outward.'],['Band Lateral Walk','Glutes / hips',3,'10–20 steps',4.0,'Keep toes forward.'],['Band Chest Press','Chest / triceps',3,'10–20',4.0,'Anchor band safely.'],['Band Chest Fly','Chest',3,'10–20',4.0,'Control the return.'],['Band Overhead Press','Shoulders / triceps',3,'10–20',4.0,'Avoid arching.'],['Band Lateral Raise','Side delts',3,'10–20',3.8,'Use light tension.'],['Band Front Raise','Front delts',3,'10–20',3.8,'Do not swing.'],['Band Row','Back / biceps',3,'10–20',4.0,'Squeeze shoulder blades.'],['Band Lat Pulldown','Lats / biceps',3,'10–20',4.0,'Anchor overhead securely.'],['Band Face Pull','Rear delts / upper back',3,'12–20',3.8,'Pull toward forehead.'],['Band Biceps Curl','Biceps',3,'10–20',3.5,'Keep elbows fixed.'],['Band Triceps Pushdown','Triceps',3,'10–20',3.5,'Keep elbows pinned.'],['Band Pallof Press','Core',3,'8–15/side',3.8,'Resist rotation.'],['Band Wood Chop','Core / shoulders',3,'8–15/side',4.0,'Rotate under control.'],['Band Calf Raise','Calves',3,'12–25',3.5,'Pause at the top.'] ],
'Tai Chi':[
['Tai Chi Warm-Up','Mobility / balance',1,'minutes',3.0,'Move slowly and breathe naturally.'],['Commencing Form','Balance / coordination',3,'repetitions',3.0,'Shift weight smoothly.'],['Parting the Wild Horse’s Mane','Balance / legs',3,'repetitions/side',3.3,'Keep posture upright.'],['White Crane Spreads Wings','Balance / coordination',3,'repetitions/side',3.0,'Use soft knees.'],['Brush Knee and Push','Balance / legs',3,'repetitions/side',3.3,'Coordinate hand and step.'],['Wave Hands Like Clouds','Balance / coordination',3,'passes',3.3,'Move continuously.'],['Golden Rooster Stands on One Leg','Balance',3,'10–30 sec/side',3.3,'Use support if needed.'],['Repulse Monkey','Balance / coordination',3,'repetitions/side',3.3,'Step carefully backward.'],['Grasp the Sparrow’s Tail','Full body coordination',3,'repetitions/side',3.3,'Keep movements rounded.'],['Tai Chi Form Practice','Balance / mobility',1,'minutes',3.3,'Use relaxed continuous motion.'] ],
'Yoga':[
['Mountain Pose','Posture / balance',2,'20–60 sec',2.5,'Stand tall and breathe.'],['Downward-Facing Dog','Shoulders / hamstrings',3,'20–45 sec',3.0,'Bend knees if needed.'],['Cobra Pose','Spine / chest',3,'15–30 sec',2.8,'Avoid forcing the lower back.'],['Sphinx Pose','Spine / chest',3,'20–45 sec',2.5,'Keep shoulders relaxed.'],['Warrior I','Legs / hips',3,'20–45 sec/side',3.2,'Square hips comfortably.'],['Warrior II','Legs / hips',3,'20–45 sec/side',3.2,'Track front knee over toes.'],['Triangle Pose','Hips / hamstrings',3,'20–45 sec/side',3.0,'Use a block if needed.'],['Tree Pose','Balance',3,'20–45 sec/side',2.8,'Avoid pressing foot into knee.'],['Chair Pose','Legs / core',3,'15–45 sec',3.5,'Keep weight balanced.'],['Bridge Pose','Glutes / back',3,'20–45 sec',3.0,'Keep knees aligned.'],['Boat Pose','Core',3,'10–30 sec',3.5,'Keep chest lifted.'],['Pigeon Pose','Hips / glutes',2,'20–60 sec/side',2.5,'Modify for knee comfort.'],['Seated Forward Fold','Hamstrings / back',2,'20–60 sec',2.5,'Hinge from hips.'],['Sun Salutation','Full body',3,'rounds',4.0,'Move with the breath.'],['Gentle Hatha Yoga','Full body / mobility',1,'minutes',2.5,'Use a comfortable pace.'],['Power Yoga','Full body / cardio',1,'minutes',4.0,'Modify demanding poses.'] ]};
const otherActivities={
'Dancing':[['Ballroom Dancing',4.5],['Line Dancing',4.5],['Country Dancing',4.8],['Social Dancing',4.5],['Ballet',5.0],['Modern Dance',5.0],['Jazz Dance',5.0],['Zumba',8.0],['Fast Dancing',7.8],['Slow Dancing',3.0]],
'Sports':[['Golf, riding cart',3.5],['Golf, walking and carrying clubs',4.8],['Golf, walking with pull cart',4.3],['Tennis, doubles',5.0],['Tennis, singles',8.0],['Pickleball',4.5],['Racquetball',7.0],['Squash',8.0],['Badminton, social',4.5],['Badminton, competitive',7.0],['Table Tennis',4.0],['Basketball, shooting hoops',4.5],['Basketball game',8.0],['Volleyball, recreational',3.0],['Beach Volleyball',8.0],['Soccer, casual',7.0],['Softball or Baseball',5.0],['Bowling',3.0],['Horseshoes',3.0],['Frisbee',3.0],['Ultimate Frisbee',8.0]],
'Outdoor':[['Hiking, moderate',6.0],['Hiking, steep hills',8.0],['Backpacking',7.0],['Walking dog',3.0],['Gardening, light',3.5],['Gardening, heavy',5.0],['Mowing lawn, push mower',5.0],['Raking leaves',4.0],['Shoveling snow',6.0],['Chopping wood',6.0],['Fishing, standing',3.5],['Hunting',5.0],['Horseback riding',4.0],['Rock climbing',8.0],['Kayaking',5.0],['Canoeing, moderate',5.8],['Paddleboarding',6.0],['Sailing',3.0],['Surfing',5.0]],
'Household & Work':[['House cleaning, light',2.5],['House cleaning, vigorous',3.5],['Vacuuming',3.3],['Mopping floors',3.5],['Washing windows',3.2],['Moving furniture',6.0],['Carrying boxes',5.0],['Painting walls',3.3],['Home repair',3.5],['Cooking and food preparation',2.5],['Shopping while walking',2.3],['Child care, active',3.5],['Playing with children',4.0],['Standing work',2.0],['Light construction work',4.5],['Heavy construction work',7.0]],
'Winter & Recreation':[['Ice Skating',7.0],['Roller Skating',7.0],['Skiing, downhill moderate',6.0],['Cross-Country Skiing',8.0],['Snowshoeing',8.0],['Sledding',5.0],['Water Skiing',6.0],['Scuba Diving',7.0],['Snorkeling',5.0],['Trampoline',4.5],['Playing Pool or Billiards',2.5],['Darts',2.5],['Miniature Golf',3.0],['Active Video Games',4.0]]};
function read(key,def){const value=state&&state[key];return value??def}function write(key,val){state[key]=val;save()}
function todayISO(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
function defaultWorkouts(){return {'Full Body Starter':['Leg Press','Seated Leg Curl','Chest Press Machine','Lat Pulldown','Seated Row Machine','Shoulder Press Machine','Abdominal Crunch Machine'],'Resistance Band Full Body':['Band Squat','Band Romanian Deadlift','Band Chest Press','Band Row','Band Overhead Press','Band Biceps Curl','Band Triceps Pushdown','Band Pallof Press'],'Full-Body Isometrics':['Wall Sit','Plank','Side Plank','Glute Bridge Hold','Push-Up Hold','Towel Row Isometric','Biceps Curl Isometric','Calf Raise Hold']}}
function ensureDefaults(){for(const key of Object.values(STORAGE))if(state[key]===undefined)state[key]={}}
function allExercises(){const out={};Object.entries(catalog).forEach(([section,items])=>items.forEach(x=>out[x[0]]={section,name:x[0],muscle:x[1],sets:x[2],reps:x[3],met:x[4],hint:x[5]}));Object.values(read(STORAGE.customExercises,{})).forEach(x=>out[x.name]=x);return out}
function getExercise(name){return allExercises()[name]}
function showTab(tab){
  const tabs=['workout','activities','builder'];
  tabs.forEach(t=>{
    const panel=document.getElementById(t+'Tab');
    const button=document.getElementById(t+'TabBtn');
    if(panel) panel.classList.toggle('hidden',t!==tab);
    if(button){
      button.classList.toggle('active',t===tab);
      button.classList.toggle('secondary',t!==tab);
    }
  });
  if(tab==='builder'){
    refreshBuilderDropdown();
    renderCatalog();
    updateSelectedCount();
  }
  if(tab==='activities'){syncActivityDate();renderActivityRows()}
  window.scrollTo({top:0,behavior:'smooth'});
}
function renderCatalog(){const host=document.getElementById('exerciseCatalog');host.innerHTML='';const sections={};Object.values(allExercises()).forEach(x=>(sections[x.section]??=[]).push(x));Object.entries(sections).forEach(([section,items])=>{const det=document.createElement('details');det.className='builder-section';det.open=false;det.innerHTML=`<summary>${escapeHtml(section)} (${items.length})</summary><div class="exercise-options">${items.sort((a,b)=>a.name.localeCompare(b.name)).map(x=>`<label class="option"><input type="checkbox" class="builderCheck" value="${escapeHtml(x.name)}" onchange="updateSelectedCount()"><span><b>${escapeHtml(x.name)}</b><span>${escapeHtml(x.muscle)} • ${x.sets} set(s) • ${escapeHtml(x.reps)}</span></span></label>`).join('')}</div>`;host.appendChild(det)})}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function updateSelectedCount(){document.getElementById('selectedCount').textContent=document.querySelectorAll('.builderCheck:checked').length}
function selectAllVisible(v){document.querySelectorAll('.builderCheck').forEach(c=>c.checked=v);updateSelectedCount()}
function addCustomExercise(){const name=document.getElementById('customExerciseName').value.trim(),section=document.getElementById('customExerciseSection').value.trim()||'Custom Exercises',muscle=document.getElementById('customExerciseMuscle').value.trim()||'Custom',sets=Math.max(1,parseInt(document.getElementById('customExerciseSets').value)||1),reps=document.getElementById('customExerciseReps').value.trim()||'reps/time',met=Math.max(1,parseFloat(document.getElementById('customExerciseMet').value)||4),hint=document.getElementById('customExerciseHint').value.trim()||'Use controlled form.';if(!name)return alert('Enter a custom exercise name.');if(getExercise(name)&&!confirm(`An exercise named “${name}” already exists. Replace it?`))return;const custom=read(STORAGE.customExercises,{});custom[name]={section,name,muscle,sets,reps,met,hint};write(STORAGE.customExercises,custom);renderCatalog();const box=[...document.querySelectorAll('.builderCheck')].find(c=>c.value===name);if(box)box.checked=true;updateSelectedCount();document.getElementById('customExerciseName').value='';document.getElementById('customExerciseHint').value='';alert(`Custom exercise added: ${name}`)}
function refreshBuilderDropdown(){const w=read(STORAGE.workouts,{});const select=document.getElementById('builderLoad');const cur=select.value;select.innerHTML='<option value="">New workout</option>'+Object.keys(w).sort().map(n=>`<option>${escapeHtml(n)}</option>`).join('');if(w[cur])select.value=cur;refreshWorkoutDropdown()}
function loadWorkoutIntoBuilder(){const name=document.getElementById('builderLoad').value;const w=read(STORAGE.workouts,{});document.getElementById('builderName').value=name;document.querySelectorAll('.builderCheck').forEach(c=>c.checked=(w[name]||[]).includes(c.value));updateSelectedCount()}
function saveWorkoutDefinition(){const name=document.getElementById('builderName').value.trim();const selected=[...document.querySelectorAll('.builderCheck:checked')].map(c=>c.value);if(!name)return alert('Enter a workout name.');if(!selected.length)return alert('Select at least one exercise.');const w=read(STORAGE.workouts,{});w[name]=selected;write(STORAGE.workouts,w);refreshBuilderDropdown();document.getElementById('builderLoad').value=name;refreshWorkoutDropdown(name);alert(`Workout saved: ${name}`)}
function deleteWorkoutDefinition(){const name=document.getElementById('builderLoad').value||document.getElementById('builderName').value.trim();if(!name)return alert('Select a saved workout first.');if(!confirm(`Delete workout “${name}”? Saved daily logs will remain.`))return;const w=read(STORAGE.workouts,{});delete w[name];write(STORAGE.workouts,w);document.getElementById('builderName').value='';document.querySelectorAll('.builderCheck').forEach(c=>c.checked=false);refreshBuilderDropdown();updateSelectedCount();refreshWorkoutDropdown();renderExercises()}
function refreshWorkoutDropdown(preferred){const w=read(STORAGE.workouts,{}),sel=document.getElementById('workoutType'),current=preferred||sel.value;sel.innerHTML=Object.keys(w).sort().map(n=>`<option>${escapeHtml(n)}</option>`).join('');if(w[current])sel.value=current}
function dayKey(){return document.getElementById('workoutDate').value}
function getPreviousForExercise(name,date){const days=read(STORAGE.days,{});for(const d of Object.keys(days).filter(x=>x<date).sort().reverse()){const found=(days[d].exercises||[]).find(e=>e.name===name);if(found&&found.sets?.some(s=>s.done))return{date:d,sets:found.sets.filter(s=>s.done)}}return null}
function bestVolumeForExercise(name,date){let best=0;Object.entries(read(STORAGE.days,{})).forEach(([d,day])=>{if(d===date)return;(day.exercises||[]).filter(e=>e.name===name).forEach(e=>{let v=0;(e.sets||[]).forEach(s=>{if(s.done)v+=(parseFloat(s.weight)||0)*(parseFloat(String(s.reps).match(/\d+(\.\d+)?/)?.[0])||0)});best=Math.max(best,v)})});return best}
function renderExercises(data=null){const w=read(STORAGE.workouts,{}),type=document.getElementById('workoutType').value,names=w[type]||[],host=document.getElementById('exerciseList'),date=document.getElementById('workoutDate').value;host.innerHTML='';document.getElementById('noWorkoutMessage').classList.toggle('hidden',names.length>0);names.forEach((name,i)=>{const x=getExercise(name);if(!x)return;const saved=(data?.exercises||[]).find(e=>e.name===name)||{};const prev=getPreviousForExercise(name,date);const div=document.createElement('div');div.className='workoutExercise';div.dataset.name=name;div.dataset.met=x.met;div.innerHTML=`<div class="exercise-title">${escapeHtml(name)}</div><span class="muscle">${escapeHtml(x.section)} • ${escapeHtml(x.muscle)}</span><div class="meta">Target: ${x.sets} set(s) × ${escapeHtml(x.reps)}. ${escapeHtml(x.hint)}</div>${prev?`<div class="previous"><b>Previous (${prev.date}):</b> ${prev.sets.map((s,j)=>`Set ${j+1}: ${s.weight||'-'} lb × ${s.reps||'-'}`).join(' • ')}</div>`:'<div class="previous"><b>Previous:</b> none saved yet</div>'}<div class="prbox">🏆 New PR for exercise volume</div><div class="badge">Est. calories: <span class="exCalories">0</span></div><div class="badge">Volume: <span class="exVolume">0</span> lb</div><div class="setgrid header"><div>Set</div><div>Weight</div><div>Reps/time</div><div>Inc?</div><div>Done</div></div>${Array.from({length:Number(x.sets)},(_,s)=>{const set=saved.sets?.[s]||{};return `<div class="setgrid"><div class="setno">${s+1}</div><input type="number" class="weight" inputmode="decimal" placeholder="lb" value="${set.weight||''}" oninput="updateSummary()"><input type="text" class="reps" placeholder="${escapeHtml(x.reps)}" value="${set.reps||''}" oninput="updateSummary()"><input type="checkbox" class="increase" ${set.increase?'checked':''} onchange="updateSummary()"><input type="checkbox" class="done" ${set.done?'checked':''} onchange="updateSummary();autoSaveDay()"></div>`}).join('')}`;host.appendChild(div)});updateSummary()}
function calcWorkoutCalories(){const lb=parseFloat(document.getElementById('bodyWeight').value)||142,kg=lb/2.20462,min=parseFloat(document.getElementById('minutes').value)||0,met=parseFloat(document.getElementById('intensity').value)||4.5;return met*3.5*kg/200*min}
function updateSummary(){let done=0,total=0,vol=0;const exs=[...document.querySelectorAll('.workoutExercise')];exs.forEach(ex=>{let ev=0,ed=0,et=0;ex.querySelectorAll('.setgrid:not(.header)').forEach(r=>{et++;total++;const w=parseFloat(r.querySelector('.weight').value)||0,reps=parseFloat(String(r.querySelector('.reps').value).match(/\d+(\.\d+)?/)?.[0])||0;ev+=w*reps;vol+=w*reps;if(r.querySelector('.done').checked){done++;ed++}});ex.querySelector('.exVolume').textContent=Math.round(ev).toLocaleString();ex.querySelector('.prbox').style.display=ev>0&&ev>bestVolumeForExercise(ex.dataset.name,dayKey())?'block':'none';ex.dataset.doneFraction=et?ed/et:0});const base=calcWorkoutCalories(),completion=total?done/total:0,wcal=base*completion;const completedShare=exs.reduce((sum,ex)=>sum+(parseFloat(ex.dataset.doneFraction)||0),0);exs.forEach(ex=>ex.querySelector('.exCalories').textContent=Math.round(wcal*(parseFloat(ex.dataset.doneFraction)||0)/(completedShare||1)));const acal=getActivityCalories(dayKey());document.getElementById('setsDone').textContent=done;document.getElementById('totalVolume').textContent=Math.round(vol).toLocaleString();document.getElementById('workoutCalories').textContent=Math.round(wcal);document.getElementById('activityCaloriesSummary').textContent=Math.round(acal);document.getElementById('totalCalories').textContent=Math.round(wcal+acal)}
function collectDay(){return{date:dayKey(),type:document.getElementById('workoutType').value,bodyWeight:document.getElementById('bodyWeight').value,minutes:document.getElementById('minutes').value,intensity:document.getElementById('intensity').value,notes:document.getElementById('notes').value,activities:read(STORAGE.activities,{})[dayKey()]||[],exercises:[...document.querySelectorAll('.workoutExercise')].map(ex=>({name:ex.dataset.name,sets:[...ex.querySelectorAll('.setgrid:not(.header)')].map(r=>({weight:r.querySelector('.weight').value,reps:r.querySelector('.reps').value,increase:r.querySelector('.increase').checked,done:r.querySelector('.done').checked}))}))}}
function saveDay(showAlert=true){if(!dayKey()){if(showAlert)alert('Select a date.');return false}const days=read(STORAGE.days,{}),d=collectDay();days[d.date]=d;write(STORAGE.days,days);renderHistory();const status=document.getElementById('saveStatus');if(status){status.textContent=`Saved ${new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`;clearTimeout(saveDay.statusTimer);saveDay.statusTimer=setTimeout(()=>status.textContent='',2500)}if(showAlert)alert(`Workout saved for ${d.date}`);return true}
function autoSaveDay(){saveDay(false)}
function loadDay(){const d=read(STORAGE.days,{})[dayKey()];if(!d){document.getElementById('notes').value='';renderExercises();updateSummary();return}refreshWorkoutDropdown(d.type);document.getElementById('workoutType').value=d.type;document.getElementById('bodyWeight').value=d.bodyWeight||142;document.getElementById('minutes').value=d.minutes||55;document.getElementById('intensity').value=d.intensity||4.5;document.getElementById('notes').value=d.notes||'';renderExercises(d)}
function clearVisible(){if(!confirm('Clear visible workout fields without deleting saved data?'))return;document.getElementById('notes').value='';renderExercises()}
function deleteCurrentDay(){if(!confirm('Delete the saved workout for this date?'))return;const days=read(STORAGE.days,{});delete days[dayKey()];write(STORAGE.days,days);loadDay();renderHistory()}
function renderHistory(){const host=document.getElementById('history'),days=read(STORAGE.days,{}),keys=Object.keys(days).sort().reverse();if(!keys.length){host.innerHTML='<p class="small">No saved workouts yet.</p>';return}host.innerHTML=keys.map(k=>{const d=days[k];let done=0,total=0,vol=0;(d.exercises||[]).forEach(e=>(e.sets||[]).forEach(s=>{total++;if(s.done)done++;vol+=(parseFloat(s.weight)||0)*(parseFloat(String(s.reps).match(/\d+(\.\d+)?/)?.[0])||0)}));return `<div class="history-item"><b>${d.date}</b> — ${escapeHtml(d.type||'Workout')}<br><span class="small">${done}/${total} sets • ${Math.round(vol).toLocaleString()} lb volume • ${Math.round(getActivityCalories(k))} activity calories</span><br><button onclick="openSaved('${k}')">Open</button></div>`}).join('')}
function openSaved(date){document.getElementById('workoutDate').value=date;loadDay();showTab('workout');window.scrollTo({top:0,behavior:'smooth'})}
function mergedActivities(){const out={};Object.entries(otherActivities).forEach(([cat,items])=>out[cat]=items.map(x=>[x[0],x[1]]));Object.values(read(STORAGE.customActivities,{})).forEach(a=>(out[a.category]??=[]).push([a.name,a.met]));return out}
function renderActivityCategories(preferred){const s=document.getElementById('activityCategory'),all=mergedActivities(),current=preferred||s.value;s.innerHTML=Object.keys(all).sort().map(x=>`<option>${escapeHtml(x)}</option>`).join('');if(all[current])s.value=current;renderActivityOptions()}
function renderActivityOptions(preferred){const cat=document.getElementById('activityCategory').value,items=mergedActivities()[cat]||[],sel=document.getElementById('activitySelect');sel.innerHTML=items.sort((a,b)=>a[0].localeCompare(b[0])).map(([n,m])=>`<option value="${m}">${escapeHtml(n)}</option>`).join('');if(preferred)[...sel.options].some(o=>{if(o.text===preferred){o.selected=true;return true}return false})}
function addCustomActivity(){const name=document.getElementById('customActivityName').value.trim(),category=document.getElementById('customActivityCategory').value.trim()||'Custom',met=Math.max(1,parseFloat(document.getElementById('customActivityMet').value)||3.5);if(!name)return alert('Enter a custom activity name.');const key=`${category}::${name}`.toLowerCase(),custom=read(STORAGE.customActivities,{});custom[key]={name,category,met};write(STORAGE.customActivities,custom);renderActivityCategories(category);renderActivityOptions(name);document.getElementById('customActivityName').value='';alert(`Custom activity saved: ${name}`)}
function syncActivityDate(){document.getElementById('activityDate').value=document.getElementById('workoutDate').value;document.getElementById('activityWeight').value=document.getElementById('bodyWeight').value}
function addActivity(){const date=document.getElementById('activityDate').value,sel=document.getElementById('activitySelect'),name=sel.options[sel.selectedIndex]?.text,met=parseFloat(sel.value),min=parseFloat(document.getElementById('activityMinutes').value);if(!date||!name||!min)return alert('Choose a date, activity, and minutes.');const all=read(STORAGE.activities,{});(all[date]??=[]).push({id:Date.now(),name,met,minutes:min,weight:parseFloat(document.getElementById('activityWeight').value)||142});write(STORAGE.activities,all);renderActivityRows();updateSummary()}
function activityCalories(a){const kg=(parseFloat(a.weight)||142)/2.20462;return (parseFloat(a.met)||1)*3.5*kg/200*(parseFloat(a.minutes)||0)}
function getActivityCalories(date){return (read(STORAGE.activities,{})[date]||[]).reduce((s,a)=>s+activityCalories(a),0)}
function renderActivityRows(){const date=document.getElementById('activityDate').value,rows=read(STORAGE.activities,{})[date]||[],host=document.getElementById('activityRows');host.innerHTML=rows.length?rows.map(a=>`<div class="activity-row activity-grid"><div><b>${escapeHtml(a.name)}</b><div class="small">MET ${a.met} • ${a.weight} lb</div></div><div>${a.minutes} min</div><div>${Math.round(activityCalories(a))} cal</div><button class="danger" onclick="deleteActivity('${date}',${a.id})">Delete</button></div>`).join(''):'<p class="small">No activities saved for this date.</p>';document.getElementById('activityTotalMinutes').textContent=Math.round(rows.reduce((s,a)=>s+(parseFloat(a.minutes)||0),0));document.getElementById('activityTotalCalories').textContent=Math.round(rows.reduce((s,a)=>s+activityCalories(a),0));updateSummary()}
function deleteActivity(date,id){if(!confirm('Delete this saved activity?'))return;const all=read(STORAGE.activities,{});all[date]=(all[date]||[]).filter(a=>a.id!==id);write(STORAGE.activities,all);renderActivityRows()}
function clearActivitiesForDate(){const date=document.getElementById('activityDate').value;if(!confirm(`Delete all other activities for ${date}?`))return;const all=read(STORAGE.activities,{});delete all[date];write(STORAGE.activities,all);renderActivityRows()}
function saveActivitiesToDay(){const date=document.getElementById('activityDate').value;if(!date)return alert('Select a date.');const days=read(STORAGE.days,{}),rows=read(STORAGE.activities,{})[date]||[];days[date]??={date,type:'Other Activities',bodyWeight:document.getElementById('activityWeight').value,minutes:0,intensity:1,notes:'',exercises:[]};days[date].activities=rows;write(STORAGE.days,days);renderHistory();const status=document.getElementById('activitySaveStatus');status.textContent=`Saved to ${date}`;clearTimeout(saveActivitiesToDay.timer);saveActivitiesToDay.timer=setTimeout(()=>status.textContent='',2500);updateSummary()}
function refreshWorkoutTracker(preferredDate){ensureDefaults();renderCatalog();refreshBuilderDropdown();refreshWorkoutDropdown();const chosen=preferredDate||document.getElementById('workoutDate').value||todayISO();const profileWeight=parseFloat(state.profile&&state.profile.weight)||142;document.getElementById('bodyWeight').value=profileWeight;document.getElementById('activityWeight').value=profileWeight;document.getElementById('workoutDate').value=chosen;document.getElementById('activityDate').value=chosen;if(!document.getElementById('workoutDate').dataset.workoutBound){document.getElementById('workoutDate').addEventListener('change',()=>{loadDay();document.getElementById('activityDate').value=dayKey()});document.getElementById('activityDate').addEventListener('change',renderActivityRows);document.getElementById('workoutDate').dataset.workoutBound='true';}renderActivityCategories();loadDay();renderHistory();renderActivityRows()}
refreshWorkoutTracker();
