'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const html=fs.readFileSync('index.html','utf8');
const duplicate=fs.readFileSync('nutrition-tracker.html','utf8');
const index=JSON.parse(fs.readFileSync('data/foods/food-index.json','utf8'));
const herbs=JSON.parse(fs.readFileSync('data/herbs-spices/herbs.json','utf8'));
const spices=JSON.parse(fs.readFileSync('data/herbs-spices/spices.json','utf8'));
const alpha=items=>items.map(x=>x.name).every((name,i,names)=>i===0||names[i-1].localeCompare(name)<=0);

for(const id of ['foodReferenceSearch','clearFoodReferenceSearchBtn','expandAllFoodGroupsBtn','collapseAllFoodGroupsBtn','herbSpiceScreen','herbSpiceSearch','clearHerbSpiceSearchBtn','foodPickerToggle','foodPickerPanel','foodPickerSearch','clearFoodPickerSearchBtn','expandAllFoodPickerBtn','collapseAllFoodPickerBtn','foodPickerGroups'])assert.ok(html.includes(`id="${id}"`),`missing ${id}`);
assert.ok(html.includes('data-screen="herbSpiceScreen">Herbs and Spices<span>'));
assert.ok(html.includes('<h1>Herbs and Spices Pairing Guide</h1>'));
assert.ok(html.includes('Flavor profile and foods they complement'));
assert.ok(!html.includes(['Herb and Spice','Encyclopedia'].join(' ')));
assert.ok(html.includes('Search by name, flavor, or complementary food'));
assert.ok(html.includes('placeholder="Search names, flavors, or foods"'));
assert.ok(html.includes('← Back to Food'));
assert.ok(html.includes("herbSpiceScreen:'foodHubScreen'"));
assert.ok(html.includes("entry.taste"));assert.ok(html.includes("entry.suggestedFoods"));
for(const forbidden of ['record.description','record.scientificName','record.alternateNames','record.culinaryUses','record.searchKeywords',['Traditional','Uses'].join(' '),['traditional','-use'].join(''),['medicinal','ly'].join(''),['record.','traditionalUses'].join(''),['record.','usageKeywords'].join('')])assert.ok(!html.includes(forbidden),`removed Herbs and Spices UI remains: ${forbidden}`);
assert.ok(!html.includes("nutrientDetails(record.nutrition||{})"));
assert.ok(!html.includes("element('h3','','Common Culinary Uses')"));
assert.ok(html.includes("image.addEventListener('error'"));assert.ok(html.includes("image.alt=entry.imageAlt"));assert.ok(html.includes("image.loading='lazy'"));assert.ok(html.includes("image.decoding='async'"));assert.ok(html.includes("image.src='assets/herbs-spices/image-unavailable.webp'"));
const rowRenderer=html.slice(html.indexOf('function createHerbSpiceRow'),html.indexOf('function herbSpiceSectionLabel'));
assert.ok(rowRenderer.includes("element('article','herbSpiceRow')"));assert.ok(rowRenderer.includes("element('div','herbSpiceName',entry.name)"));assert.ok(rowRenderer.includes("element('div','herbSpiceTaste',entry.taste)"));assert.ok(rowRenderer.includes("element('div','herbSpiceFoods'"));assert.ok(rowRenderer.includes('row.append(imageCell,nameCell,tasteCell,foodsCell)'));
assert.ok(!rowRenderer.includes('details'));assert.ok(!rowRenderer.includes('summary'));assert.ok(!html.includes('herbSpiceCard'));assert.ok(!html.includes('Taste and Suggested Foods'));
for(const heading of ['Image','Name','Flavor','Pairs Well With'])assert.ok(html.includes(`element('div','',\'${heading}\')`)||html.includes(`element('div','','${heading}')`),`missing table heading ${heading}`);
for(const banner of ['HERBS A–F','HERBS G–M','HERBS O–W','SPICES A–C','SPICES C–M','SPICES M–W'])assert.ok(html.includes(`'${banner}'`),`missing ${banner}`);

assert.ok(index.total>=300);assert.ok(index.groups.length>=10);
assert.deepStrictEqual(index.groups.map(x=>x.group),[...index.groups.map(x=>x.group)].sort((a,b)=>a.localeCompare(b)));
let total=0;for(const meta of index.groups){const items=JSON.parse(fs.readFileSync(path.join('data','foods',meta.file),'utf8'));assert.strictEqual(items.length,meta.count);assert.ok(alpha(items));assert.ok(items.every(x=>x.nutritionBasis==='per 100 g'));total+=items.length;}assert.strictEqual(total,index.total);
assert.strictEqual(herbs.length,33);assert.strictEqual(spices.length,45);assert.ok(alpha(herbs));assert.ok(alpha(spices));
const allowedFields=['id','name','type','taste','suggestedFoods','image','imageAlt'],flavorWords=/spicy|sweet|savory|earthy|smoky|peppery|bitter|pungent|citrusy|floral|woody|nutty|warm|fresh|grassy|minty|pine-like|licorice-like|tangy|mild|hot|aromatic|tart|sour|fruity|sharp|resinous|anise-like|celery-like|onion-like/i,images=new Set;
for(const record of [...herbs,...spices]){assert.deepStrictEqual(Object.keys(record).sort(),[...allowedFields].sort(),`${record.name} schema`);for(const key of allowedFields)assert.ok(record[key],`${record.name} ${key}`);assert.ok(record.type==='herb'||record.type==='spice');assert.strictEqual(typeof record.taste,'string');assert.ok(record.taste.length>10&&flavorWords.test(record.taste),`${record.name} useful taste`);assert.ok(Array.isArray(record.suggestedFoods)&&record.suggestedFoods.length>=4&&record.suggestedFoods.length<=10);assert.ok(record.suggestedFoods.every(x=>typeof x==='string'&&x.trim()),`${record.name} suggested foods`);assert.ok(!/^https?:\/\//i.test(record.image),`${record.name} local image`);assert.ok(!images.has(record.image),`${record.name} unique image`);images.add(record.image);assert.ok(fs.existsSync(record.image)&&fs.statSync(record.image).size>0,`${record.name} image file`);const image=fs.readFileSync(record.image);assert.strictEqual(image.subarray(0,4).toString(),'RIFF');assert.strictEqual(image.subarray(8,12).toString(),'WEBP');}
const normalize=value=>String(value).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const search=(items,q)=>items.filter(item=>normalize([item.name,item.taste,...item.suggestedFoods].join(' ')).includes(normalize(q)));
assert.ok(search(herbs,'bAs').some(x=>x.name==='Basil'));assert.ok(search(spices,'GING').some(x=>x.name==='Ginger'));
for(const query of ['spicy','sweet','savory','smoky','earthy','fish','pork','chicken','pasta','soup','vegetables','dessert'])assert.ok(search([...herbs,...spices],query).length,`culinary search: ${query}`);
assert.ok(search([...herbs,...spices],'tart').length>=5);assert.ok(search([...herbs,...spices],'SWE').length>1,'partial and case-insensitive search');
assert.ok(html.includes("normalize('NFD').replace(/[\\u0300-\\u036f]/g,''"));assert.ok(html.includes('function herbSpiceMatches(entry,query)'));assert.ok(html.includes("encyclopediaReference.query=normalizeHerbSpiceSearch"));assert.ok(html.includes('No herbs or spices match your search.'));assert.ok(html.includes("encyclopediaReference.query=''"));
assert.ok(!html.includes('expandAllHerbSpiceBtn'));assert.ok(!html.includes('collapseAllHerbSpiceBtn'));assert.ok(!html.includes('setAllHerbSpiceSections'));
assert.ok(html.includes('.herbSpiceTableHead,.herbSpiceRow{display:grid'));assert.ok(html.includes('@media(max-width:700px)'));assert.ok(html.includes('.herbSpiceTaste::before{content:"Flavor: "'));assert.ok(html.includes('.herbSpiceFoods::before{content:"Pairs Well With: "'));
assert.ok(html.includes('Herbs and Spices could not be loaded. Please try again.'));assert.ok(html.includes("console.error('Herbs and Spices data load failed'"));

assert.ok(html.includes('role="combobox"'));assert.ok(html.includes('role="listbox"'));assert.ok(html.includes("event.key==='Escape'"));assert.ok(html.includes("picker.contains(event.target)"));
assert.ok(html.includes("const groups=pickerLegacyGroups()"));assert.ok(html.includes("foodReference.index.groups"));assert.ok(html.includes("items.map(pickerReferenceChoice)"));assert.ok(html.includes("f.custom?'Custom Foods'"));
assert.ok(html.includes("selectedFoodChoice?.kind==='reference'?referenceFoodSnapshot"));assert.ok(html.includes("state.foods[selectedFoodChoice?.index"));
assert.ok(!html.includes("encyclopediaReference.sections")||!html.includes("encyclopediaReference.sections.map(pickerReferenceChoice)"),'culinary records must not feed selector');
assert.ok(html.includes("foodPickerState.expanded.clear()"));assert.ok(html.includes("open=!!query||foodPickerState.expanded.has(name)"));assert.ok(html.includes("normalizedSearch(`${x.name} ${name}`).includes(query)"));assert.ok(html.includes("foodPickerState.query=''"));assert.ok(html.includes('No foods match your search.'));
assert.ok(html.includes('.foodPickerGroupHeader{')&&html.includes('font-weight:700;font-size:1.05rem'));
const pickerCss=html.slice(html.indexOf('.foodPickerGroupHeader{'),html.indexOf('.foodPickerItems{'));assert.ok(!/#(?:ef4444|dc2626|b91c1c|7f1d1d)|\bred\b/i.test(pickerCss),'selector headers must not be red');
assert.ok(html.includes('overflow-wrap:anywhere'));assert.ok(!html.includes('innerHTML=foodPickerState.query'));
assert.ok(html.includes("candidate.entries.map(copyKnownEntryFields)"));assert.ok(html.includes("entries:(state.entries||[]).map(copyKnownEntryFields)"));
assert.strictEqual(html,duplicate,'HTML entry points must remain identical');
console.log(`Food reference tests: PASS (${index.total} foods, grouped Today selector, ${herbs.length} herbs, ${spices.length} spices)`);
